/* Embedded CUDA module images generated by the Makefile. */
#ifndef _CUDA_EMBEDDED_H_
#define _CUDA_EMBEDDED_H_

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char msieve_stage1_core_fatbin[];
extern const unsigned char msieve_stage1_core_ptx[];
extern const unsigned char msieve_lanczos_kernel_fatbin[];
extern const unsigned char msieve_lanczos_kernel_ptx[];

#ifdef __cplusplus
}
#endif

#endif /* !_CUDA_EMBEDDED_H_ */
